(16, 1)
EPOCH: 1
TRAINING LOSS :2.30297137970908
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3028782321748626
VALIDATION ACCURACY :0.099
EPOCH: 2
TRAINING LOSS :2.302966844919708
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302883065278211
VALIDATION ACCURACY :0.099
EPOCH: 3
TRAINING LOSS :2.3029626361953928
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3028880796663915
VALIDATION ACCURACY :0.099
EPOCH: 4
TRAINING LOSS :2.3029586472997883
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3028923917840625
VALIDATION ACCURACY :0.099
EPOCH: 5
TRAINING LOSS :2.3029550272151513
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302897169409421
VALIDATION ACCURACY :0.099
EPOCH: 6
TRAINING LOSS :2.302951541638618
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302901455453599
VALIDATION ACCURACY :0.099
EPOCH: 7
TRAINING LOSS :2.302948414486088
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3029058400887688
VALIDATION ACCURACY :0.099
EPOCH: 8
TRAINING LOSS :2.302945563169657
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3029103367867774
VALIDATION ACCURACY :0.099
EPOCH: 9
TRAINING LOSS :2.302942907914655
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302914869813541
VALIDATION ACCURACY :0.099
EPOCH: 10
[34m[1mwandb[39m[22m: Network error resolved after 0:00:53.584254, resuming normal operation.
TRAINING LOSS :2.302940216749103
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3029185351857957
VALIDATION ACCURACY :0.099
EPOCH: 11
TRAINING LOSS :2.3029379836578423
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3029224546476907
VALIDATION ACCURACY :0.099
EPOCH: 12
TRAINING LOSS :2.302935847879237
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302926496820826
VALIDATION ACCURACY :0.099
EPOCH: 13
TRAINING LOSS :2.302933749119851
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.30293030457041
VALIDATION ACCURACY :0.099
EPOCH: 14
TRAINING LOSS :2.302931778961726
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.30293391681307
VALIDATION ACCURACY :0.099
EPOCH: 15
TRAINING LOSS :2.302930037684442
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302937658432683
VALIDATION ACCURACY :0.099
EPOCH: 16
TRAINING LOSS :2.302928251727183
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302941646978739
VALIDATION ACCURACY :0.099
EPOCH: 17
TRAINING LOSS :2.302926701408401
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3029448138594977
VALIDATION ACCURACY :0.099
EPOCH: 18
TRAINING LOSS :2.302925387814398
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3029483266400246
VALIDATION ACCURACY :0.099
EPOCH: 19
TRAINING LOSS :2.3029240879366433
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3029524056423165
VALIDATION ACCURACY :0.099
EPOCH: 20
TRAINING LOSS :2.302922846088538
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302955746816978
VALIDATION ACCURACY :0.099
EPOCH: 21
TRAINING LOSS :2.302921608479081
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.3029589639189907
VALIDATION ACCURACY :0.099
EPOCH: 22
TRAINING LOSS :2.302920533339447
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.30296217185626
VALIDATION ACCURACY :0.099
EPOCH: 23
TRAINING LOSS :2.302919339258572
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302965315959283
VALIDATION ACCURACY :0.099
EPOCH: 24
TRAINING LOSS :2.302918374942319
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.30296791208123
VALIDATION ACCURACY :0.099
EPOCH: 25
TRAINING LOSS :2.3029175708468914
TRAINING ACCURACY :0.10011111111111111
VALIDATION LOSS :2.302971160317136
VALIDATION ACCURACY :0.099
I do not see signs of further improvement. Therefore, Ending training..
Stopping early at epoch 25: Accuracy too low (0.10)
 Testing on unseen data
TEST LOSS :2.3029197292724137
TEST ACCURACY :0.1
Traceback (most recent call last):
  File "C:\Users\shrey\OneDrive\Desktop\Mtech\SEMESTER-2\DL\DL Assignment-1\sweep_train.py", line 45, in <module>
    sweep_train()
  File "C:\Users\shrey\OneDrive\Desktop\Mtech\SEMESTER-2\DL\DL Assignment-1\sweep_train.py", line 35, in sweep_train
    model.fit(x_val, y_ohv_val, x_train, y_ohv_train, X_test, Y_ohv_test)
  File "C:\Users\shrey\OneDrive\Desktop\Mtech\SEMESTER-2\DL\DL Assignment-1\Model1.py", line 311, in fit
    pkl.dump(MyDicts, open("model_final.p", "wb" ))
    ^^^
NameError: name 'pkl' is not defined